# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'NET45-Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Castle.Transaction nuspec'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src'
    Contents: '**\*.nuspec'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Castle.Transaction build output'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Castle.Services.Transaction\bin\NET45-Release'
    Contents: '**\Castle.Services.Transaction.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Castle.Services.Transaction\build-output'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Castle.Facilities.AutoTx build output'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Castle.Facilities.AutoTx\bin\NET45-Release'
    Contents: '**\Castle.Facilities.AutoTx.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Castle.Facilities.AutoTx\build-output'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Castle.Services.Transaction Source Code'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Castle.Services.Transaction'
    Contents: '**\*.cs'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Castle.Services.Transaction\src'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy Castle.Facilities.AutoTx Source Code'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Castle.Facilities.AutoTx'
    Contents: '**\*.cs'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Castle.Facilities.AutoTx\src'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'